### ISSUE TITLE
Access denied for user 'root'@'localhost'

### ISSUE THREAD

**Issue by quixand** [beatsbears/macos_burst#4]
I'm seeing the following error. 
OSX Sierra 10.12.6

```==> Summary
🍺  /usr/local/Cellar/mariadb/10.2.14: 641 files, 170MB
\033[92m\n[+] Starting MariaDB...\033[0m
Service `mariadb` already started, use `brew services restart mariadb` to restart.
\033[92m\n[+] Resetting Root password for MariaDB...\033[0m
\033[92m    Press ENTER when prompted.\033[0m
Enter password:
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
\033[92m\n[+] Creating burstwallet db...\033[0m
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
\033[92m[+] Database created successfully...\033[0m
\033[92m\n[+] Installing Java 8 JDK...\033[0m
```

after that the java process does not start, a manual run produces the following

```$ ./burst.sh
Apr 08, 2018 11:08:53 AM brs.Burst loadProperties
INFO: Initializing Burst Reference Software (BRS) version 2.0.3
Apr 08, 2018 11:08:53 AM org.ehcache.core.EhcacheManager createCache
INFO: Cache 'account' created in EhcacheManager.
[INFO] 2018-04-08 11:08:53 brs.db.sql.Db - Using mariadb Backend
[SEVERE] 2018-04-08 11:08:53 brs.Burst - java.lang.RuntimeException: Invalid database charset >utf8< - needs to be >utf8mb4<
java.lang.RuntimeException: java.lang.RuntimeException: Invalid database charset >utf8< - needs to be >utf8mb4<
	at brs.db.mariadb.MariadbDbVersion.init(MariadbDbVersion.java:51)
	at brs.db.mariadb.MariadbDbs.<init>(MariadbDbs.java:23)
	at brs.db.sql.Db.getDbsByDatabaseType(Db.java:120)
	at brs.Burst.loadWallet(Burst.java:197)
	at brs.Burst.init(Burst.java:176)
	at brs.Burst.main(Burst.java:157)
Caused by: java.lang.RuntimeException: Invalid database charset >utf8< - needs to be >utf8mb4<
	at brs.db.mariadb.MariadbDbVersion.init(MariadbDbVersion.java:26)
	... 5 more
[INFO] 2018-04-08 11:08:53 brs.Burst - Shutting down...```

**Comment by quixand** [comment]
I think I've found the problem. When prompted for the password, which at that point, is blank for the new DB, I typed 'admin'. this screwed up the install flow and put the DB in a weird state.

I manually dropped the burstwallet user and schema and manually re-configured the DB. The java process has now started ok.

The script output on line 199 is a little misleading
```echo "\033[92m[+] Database created successfully...\033[0m"```
this is still printed and the script continues if the SQL fails.

**Comment by beatsbears** [comment]
Good catch, @quixand. I'll add some logic to actually check that the DB exists after creation.

**Comment by beatsbears** [comment]
The latest update will no longer ask you to press anything during the mariaDB/wallet setup phase of the script, which should hopefully avoid any confusion. It will also check after the mariaDB commands have run to be sure the db was created successfully. 👍
